name: Build executable binarys
on: [push, pull_request]
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          substituters = https://cache.nixos.org https://nixcache.reflex-frp.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI=
          binary-caches-parallel-connections = 40
    -
      uses: cachix/cachix-action@v10
      with:
        name: thekk
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    -
      name: Build executables
      run: nix-build --max-jobs auto -A exe
