name: Release process
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          substituters = https://cache.nixos.org https://nixcache.reflex-frp.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI=
          binary-caches-parallel-connections = 40
    -
      uses: cachix/cachix-action@v10
      with:
        name: thekk
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    -
      name: Build docker image
      run: nix-build --max-jobs auto ./docker.nix
    -
      run: docker load < result
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    -
      name: Push docker image to GitHub Container Registry
      run: |
        OWNER=$(echo ${{ github.repository_owner }} | tr '[A-Z]' '[a-z]')
        IMAGE=$(nix eval --impure --raw --expr '(import ./docker.nix {}).imageName' | tr '[A-Z]' '[a-z]')
        BRANCH_TAG=$(echo ${{ github.ref }} | cut -d '/' -f 3)
        REGISTRY_URL=ghcr.io/$OWNER/$IMAGE

        docker tag $IMAGE "$REGISTRY_URL:$BRANCH_TAG"
        docker push "$REGISTRY_URL:$BRANCH_TAG"

        docker tag $IMAGE "$REGISTRY_URL:latest"
        docker push "$REGISTRY_URL:latest"
